<?php
/** @var \JerVoo\Breadcrumbs\Block\Html\Breadcrumbs $block */
if ($block->getCrumbs()) :
?>
<div class="breadcrumbs-outer">
    <div class="breadcrumbs">
        <ul class="items">
            <?php foreach($block->getCrumbs() as $crumbName => $crumbInfo) : ?>
                <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                           title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        </a>
                    <?php elseif ($crumbInfo['last']) : ?>
                        <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                    <?php else : ?>
                        <?= $block->escapeHtml($crumbInfo['label']) ?>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
<?php endif ?>